ARG SCHEME=chibi
ARG IMAGE=chibi:latest
FROM docker.io/schemers/${IMAGE}
ARG SCHEME=chibi
ENV COMPILE_R7RS=${SCHEME}
RUN apt-get update && apt-get install -y make
COPY configure .
COPY Makefile .
COPY compile-r7rs .
RUN ./configure
RUN make
RUN make install
