;;;; retropikzel.pffi.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (scheme#eval
      '(import-syntax
         (only scheme.base
               begin
               cond-expand
               export
               import
               import-for-syntax
               include
               include-ci
               syntax-rules)
         (only chicken.module export/rename)
         scheme.base
         scheme.write
         scheme.char
         scheme.file
         scheme.process-context
         chicken.base
         chicken.foreign
         chicken.locative
         chicken.syntax
         chicken.memory
         chicken.random))
    (import
      (only scheme.base
            begin
            cond-expand
            export
            import
            import-for-syntax
            include
            include-ci
            syntax-rules))
    (##sys#register-compiled-module
      'retropikzel.pffi
      '#f
      (scheme#list)
      '()
      (scheme#list
        (scheme#cons
          '|\x4;r7rsretropikzel.pffi|
          (##sys#er-transformer (##core#lambda (x r c) (##core#undefined)))))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
